### ISSUE TITLE
Conditional Expression parser

### ISSUE THREAD

**Issue by Alfriadox** [Wright-Language-Developers/Wright-lang#10]
Conditional expression parser tracking issue. 

Syntax should be along the lines of 
```
"if", expr, block, ("else", "if", expr, block)*, ["else", block] 
```

**Comment by kvverti** [comment]
Should `if` also accept single expressions? i.e.
```
if expr1
  expr2
```

**Comment by io12** [comment]
What would the type of that expression be?

**Comment by kvverti** [comment]
I would assume the type would be the least upper bound of all the branches, with short `if`s being treated as having an implicit `else <unit-type>`.

**Comment by kvverti** [comment]
@Alfriadox and I brainstormed result types for if expressions and suggested a [disjoint union](https://en.m.wikipedia.org/wiki/Disjoint_union) result type if the then and else branches have different types.

**Comment by io12** [comment]
We could also do it the rust way and require that both branches be the same type.

**Comment by Alfriadox** [comment]
Yeah I'm leaning towards the rust way. We would need to do some special stuff though, like rust, to make 
```
if (val) {return a}
else {return b}
```
and 
```
if (val) {return a}
return b
```
act the same

**Comment by Alfriadox** [comment]
I think we need to think about returns as sorta a special case. They aren't exactly expressions and they should be able to choose what scope they return from.

**Comment by io12** [comment]
https://doc.rust-lang.org/std/primitive.never.html

**Comment by kvverti** [comment]
Yep, I agree that `return` expressions should be the bottom type. With regards to parsing, since conditionals are expressions, we can write
```
return if val { a } else { b }
```
instead of using two separate returns

**Comment by kvverti** [comment]
I would go further tho and consider the bottom type to have implemented all traits. If we are adding a false type then we better make it as false as possible :)

**Comment by Alfriadox** [comment]
Anything that returns void can be just `if cond {block}` and not require the empty else block. I am looking at the rust grammar right now and I thing we should follow that as closely as possible.
