### ISSUE TITLE
Block Parser

### ISSUE THREAD

**Issue by kvverti** [Wright-Language-Developers/Wright-lang#12]
```
Block ::= "{" [[Expression [";"]] "}"
```

Notes:
* Blocks do not need an expression list because the semicolon `;` is a binary operator.
* The unit value (of the type `void`) might be expressed as `{}`.

Treating blocks as expressions that return the value of `Expression` poses a parsing question: should blocks be valid anywhere an expression is? Examples include
```
3 + { "hello"; 4 }
func(3, { 2; 1 })
```
In this case, if `;` keeps being an operator, blocks have the same grouping properties as parentheses `()`. 
```
3 + ("hello"; 4)
func(3, (2; 1))
```
Should parenthesized expressions also be considered blocks by the grammar?

**Comment by io12** [comment]
One thing I can think of to resolve the issues in https://github.com/Wright-Language-Developers/Wright-lang/issues/13 is to make `;` not a binary operator and instead make blocks braces surrounding expressions separated by semicolons.

**Comment by io12** [comment]
This way a block could be represented by `Vec<Expression>`.

**Comment by kvverti** [comment]
This would make blocks
```
Block ::= "{" [Expression (";" Expression)* [";"]] "}"
```

**Comment by kvverti** [comment]
For now I'm implementing blocks as a list of semicolon-terminated expressions.
```
Block ::= "{" (Statement)* [Expression] "}"
Statement ::= Expression ";"
```
