### ISSUE TITLE
Multiline comments

### ISSUE THREAD

**Issue by Alfriadox** [Wright-Language-Developers/Wright-lang#19]
Once #18 is merged we will need to add on to and modify it to also work for multiline comments. This is the tracking issue for that.

**Comment by io12** [comment]
`/* this syntax */`?

Also, should nested comments be supported? (Rust seems to allow this, but C doesn't)

**Comment by kvverti** [comment]
Note that there are problems with nested comments. The canonical example:
```
/*
let x = "comment start token /*";
*/
```
I suggest not allowing nested comments. Maybe we can add a dedicated way to comment out code.

**Comment by io12** [comment]
Rust probably handles this by ignoring the insides of strings during comment parsing.

**Comment by kvverti** [comment]
Some questions to think about:
- do we encourage multiline comments for documentation?
- do we see a need to comment out the middle of a line?

If neither are true, we don't need multiline comments. If only the second is true, then we can have two variants of single line comments.
